version: '3.3'

networks:
  dev:
    driver: bridge

services:
  workout-container:
    image: farukerat/webhook-image:latest
    container_name: webhook-app
    ports:
      - "8084:80"
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    networks:
      - dev
    volumes:
      - repos-data:/repos

volumes:
  repos-data:
